### ISSUE TITLE
Problems after upgrade.

### ISSUE THREAD

**Issue by debenedettohernan** [MetinOpenBot/OpenBot#5]
Hello, good morning. I am a player of the spanish server and a few hours ago made update and when I want to run the injector closes the game. 
Greetings

**Comment by coderex96** [comment]
The developer update offsets, should be resolved https://discord.com/channels/861727039450120242/861735845165924392

**Comment by debenedettohernan** [comment]
Hello, the discord link does not work

**Comment by coderex96** [comment]
Sorry, try now

**Comment by debenedettohernan** [comment]
![image](https://user-images.githubusercontent.com/80839930/132698156-870dd85e-6f0f-4849-baf6-4c053ec82b91.png)

still not working
